# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - "src/"

    patch:
      default:
        target: auto
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "**/*_test.py"
  - "**/test_*.py"
  - "setup.py"
  - "**/__pycache__/**"
  - "dist/"
  - "build/"
  - "*.egg-info/"
  - ".github/"
  - "docs/"

flags:
  unittests:
    paths:
      - src/
    carryforward: false

  test-results:
    carryforward: false
